### ISSUE TITLE
Attend : check mask isn't already 4D

### ISSUE THREAD

**Issue by pfeatherstone** [lucidrains/recurrent-memory-transformer-pytorch#12]
https://github.com/lucidrains/recurrent-memory-transformer-pytorch/blob/98bf3091a29fbd65dbbb30ce00dd1cadd05fef2d/recurrent_memory_transformer_pytorch/attend.py#L125-L127

We should check `mask` isn't already 4D.

**Comment by lucidrains** [comment]
oh yup, fixed!
