### ISSUE TITLE
Question: why do we need read_memory_emb

### ISSUE THREAD

**Issue by pfeatherstone** [lucidrains/recurrent-memory-transformer-pytorch#14]
https://github.com/lucidrains/recurrent-memory-transformer-pytorch/blob/976af1ecba5c1b421a4e204aab31b297c4302b81/recurrent_memory_transformer_pytorch/recurrent_memory_transformer.py#L259

https://github.com/lucidrains/recurrent-memory-transformer-pytorch/blob/976af1ecba5c1b421a4e204aab31b297c4302b81/recurrent_memory_transformer_pytorch/recurrent_memory_transformer.py#L337-L342

Why do we need `self.read_memory_emb` ? They are not used if `read_memories is None`. So why not just use `read_memories` ?

**Comment by pfeatherstone** [comment]
Also, why this:
https://github.com/lucidrains/recurrent-memory-transformer-pytorch/blob/976af1ecba5c1b421a4e204aab31b297c4302b81/recurrent_memory_transformer_pytorch/recurrent_memory_transformer.py#L369-L376

**Comment by lucidrains** [comment]
> https://github.com/lucidrains/recurrent-memory-transformer-pytorch/blob/976af1ecba5c1b421a4e204aab31b297c4302b81/recurrent_memory_transformer_pytorch/recurrent_memory_transformer.py#L259
> 
> https://github.com/lucidrains/recurrent-memory-transformer-pytorch/blob/976af1ecba5c1b421a4e204aab31b297c4302b81/recurrent_memory_transformer_pytorch/recurrent_memory_transformer.py#L337-L342
> 
> Why do we need `self.read_memory_emb` ? They are not used if `read_memories is None`. So why not just use `read_memories` ?

so this was a finding in the paper somewhere, iirc

they found that when attending to the memories, to allow each memory token to fully differentiate into something that does not overlap with another memory token, they needed to inject learned positions at each step. i should probably rename `read_memory_emb` to something like `read_memory_positions`

**Comment by lucidrains** [comment]
> Also, why this:
> 
> https://github.com/lucidrains/recurrent-memory-transformer-pytorch/blob/976af1ecba5c1b421a4e204aab31b297c4302b81/recurrent_memory_transformer_pytorch/recurrent_memory_transformer.py#L369-L376

that's an attempt to maintain usage of rotary positions, while allowing the network to distinguish between sequence tokens to memory tokens

**Comment by pfeatherstone** [comment]
Thanks!

**Comment by pfeatherstone** [comment]
> > Also, why this:
> > https://github.com/lucidrains/recurrent-memory-transformer-pytorch/blob/976af1ecba5c1b421a4e204aab31b297c4302b81/recurrent_memory_transformer_pytorch/recurrent_memory_transformer.py#L369-L376
> 
> that's an attempt to maintain usage of rotary positions, while allowing the network to distinguish between sequence tokens to memory tokens

Did you find that not doing this had undesirable consequences ?

**Comment by lucidrains** [comment]
@pfeatherstone i don't have any formal experiments to back it up, just makes sense to me with my current intuition. feel free to run the experiments and show me otherwise
