### ISSUE TITLE
flash attention, and a potentially better improvement

### ISSUE THREAD

**Issue by Alignment-Lab-AI** [lucidrains/recurrent-memory-transformer-pytorch#2]
hello! sorry to bother you, but considering flash attention isnt currently compatible with relative positional embeddings - do you intend to work around that or update the codebase?

the implementation i came up with last night (before there was a git lol) turned out to be quite a bit different than this one. i wound up trying to adapt it to a t5, theres still more work to be done but there may be space in there to utilize the flash attention stuff, especially considering the alternate ways that ive got in there to adapt/simulate relative positional embeddings. figured id link it for you to look at in case something happened to be useful to you, i found your github acc last night and its going to be wildly useful to me so im just wanting to return the favor as best i can :)

https://github.com/Alignment-Lab-AI/RMT5-HYENA

**Comment by lucidrains** [comment]
@Alignment-Lab-AI oh hey! so i was planning on a rotary embedding solution, which flash attention would be compatible with. just need to make sure the memory has sufficient distance from the main sequence positions

**Comment by lucidrains** [comment]
yea i have, but i haven't seen any breakout SOTA results from the state spaces line of research yet, despite the hype. until then, i will probably stick with attention

**Comment by lucidrains** [comment]
@Alignment-Lab-AI for hyena, i will probably give it a try for genomics later this year, but if it doesn't work on the first try, just turn to hierarchical attention

**Comment by Alignment-Lab-AI** [comment]
i was planning on implementing it as a second head too, ill let you know if anything crazy happens!

**Comment by lucidrains** [comment]
ok rotary added! closing the issue
