### ISSUE TITLE
What is the reasoning for no dropout?

### ISSUE THREAD

**Issue by luchris429** [lucidrains/recurrent-memory-transformer-pytorch#22]
https://github.com/lucidrains/recurrent-memory-transformer-pytorch/blob/d45ef72a40324c6224ffacb890d5593a69db73de/recurrent_memory_transformer_pytorch/recurrent_memory_transformer.py#L135

**Comment by lucidrains** [comment]
@luchris429 for a while, there was this new fad of not doing dropouts for LLMs, simply because OpenAI stopped doing them as they scaled up

now i see papers [like this](https://arxiv.org/abs/2305.16179) and realize nobody really knows what they are doing. yea, let's get the dropouts back in there.

**Comment by luchris429** [comment]
ahh I did not know. thanks for the context!
