### ISSUE TITLE
Is rmt compatible with pretrain models like LLaMA？

### ISSUE THREAD

**Issue by yw2278** [lucidrains/recurrent-memory-transformer-pytorch#7]
Thank you for implementing the rmt in pytorch, very helpful! 
I want to use this in LLaMa to  increase the input length, is rmt suitable for gpt-like models?

**Comment by lucidrains** [comment]
@yw2278 the benefit of the RMT architecture is its simplicity

you'll have to modify llama to accept memory tokens and do a bit of fine tuning

the tricky part with llama is making sure attention to and from the memory tokens have no rotated positions

an alternative that could work is to treat the last N tokens as the memory tokens, and perhaps the network will learn to use them to store memories for the next segment. it probably won't be as good as having dedicated memory tokens though

**Comment by lucidrains** [comment]
@yw2278 short answer, yes, you can probably finetune a pretrained model with this scheme

**Comment by yw2278** [comment]
Thanks! I will research on it

**Comment by yw2278** [comment]
> @yw2278 the benefit of the RMT architecture is its simplicity
> 
> you'll have to modify llama to accept memory tokens and do a bit of fine tuning
> 
> the tricky part with llama is making sure attention to and from the memory tokens have no rotated positions
> 
> an alternative that could work is to treat the last N tokens as the memory tokens, and perhaps the network will learn to use them to store memories for the next segment. it probably won't be as good as having dedicated memory tokens though

Nice Idea!

**Comment by sentialx** [comment]
@yw2278 Did you found any solution for that?

**Comment by Alignment-Lab-AI** [comment]
:)
